tmplPreliminar= """ {
	 "id":"{{id_pre}}" ,
	 "folio_evento":"{{folio_evento_pre}}" ,
	 "tipo_evento":"{{tipo_evento_pre}}" , 
	 "delegacion":"{{delegacion_pre}}" ,
	 "comandancia":"{{comandancia_pre}}" , 
	 "turno":"{{turno_pre}}" , 
	 "hora_evento":"{{hora_evento_pre}}" , 
	 "fecha_evento":"{{fecha_evento_pre}}" , 
	 "localizacion_evento":"{{localizacion_evento_pre}}" , 
	 "observaciones_evento":"{{observaciones_evento_pre}}" , 
	 "reg_inicio":"{{reg_inicio_pre}}" , 
	 "reg_final":"{{reg_final_pre}}" , 
	 "cabina_completo":"{{cabina_completo_pre}}" ,
	 "activo":"{{activo_pre}}" , 
	 "id_unico":"{{id_unico_pre}}" , 
	 "tipo_operativo":"{{tipo_operativo_pre}}" , 
	 "agente_intervino":"{{agente_intervino_pre}}" , 
	 "unidad_intervino":"{{unicad_inteervino_pre}}" , 
	 "sector_intervino":"{{sector_intervino_pre}}" ,
	 "id_tipo_accidente":"{{it_tipo_accidente_pre}}" , 
	 "id_clasificacion":"{{id_clasificacion_pre}}" , 
	 "no_veh_participantes":"{{no_veh_participantes_pre}}" , 
	 "no_muertos":"{{no_muertos_pre}}" , 
	 "no_heridos":"{{no_heridos_pre}}" ,
	 "no_detenidos":"{{no_detenidos_pre}}" , 
	 "id_pension":"{{id_pension_pre}}" , 
	 "usuario":"{{usuario_pre}}" , 
	 "por_llenar":"{{por_llenar_pre}}" , 
	 "colonia":"{{colonia_pre}}" ,
	 "no_inventario":"{{no_inventario_pre}}" 
	}
"""