#-*- coding: utf-8 -*-import time
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.enums import *
from reportlab.lib.pagesizes import *
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.rl_config import defaultPageSize
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import login_required
from systra.settings import STATICFILES_DIRS
PAGE_WIDTH=defaultPageSize[0]
PAGE_HEIGHT=defaultPageSize[1]
logo="escudo_transito.jpg"
class GenerateInventarioPdf:
	def __init__(self,data,ruta):
		self.data= data
		self.ruta= ruta
	def build_pdf(self): 
		doc = SimpleDocTemplate(self.ruta,pagesize=letter,
                        rightMargin=10,leftMargin=10,
                        topMargin=72,bottomMargin=18)
		Story=[]
 		styles=getSampleStyleSheet()
		styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
		styles.add(ParagraphStyle(name='Centro', alignment=TA_CENTER))
		styles.add(ParagraphStyle(name='izq', alignment=TA_LEFT))
		styles.add(ParagraphStyle(name='der', alignment=TA_RIGHT))
		Story.append(Spacer(1, 12))
		Story.append(Spacer(1, 12))
		Story.append(Spacer(1, 12))
		Story.append(Spacer(1, 12))
		Story.append(Spacer(1, 12))
		Story.append(Spacer(1, 12))
		doc.build(Story,onFirstPage=self.myFirstPage)
	def myFirstPage(self,canvas, doc):
		canvas.saveState()
		fields=self.data
		canvas.drawImage(STATICFILES_DIRS[0]+'escudo_transito.jpg',10, PAGE_HEIGHT-120)
		canvas.setFont('Times-Bold',9)
		canvas.drawString(250,PAGE_HEIGHT-70, 'ENTREGA DE VEHICULO')
		canvas.setFont('Times-Roman',8)
		canvas.drawString(450,PAGE_HEIGHT-70, 'Folio de Inventario')
		canvas.setFont('Times-Bold',12)
		folio_inventario=fields.get('folio_inventario',"")
		canvas.drawString(520,PAGE_HEIGHT-70, folio_inventario)
		canvas.drawString(10,PAGE_HEIGHT+100, 'HOLA ESTO ES UNA PRUEBA')
		canvas.setFont('Times-Bold',9)
		canvas.drawString(190,PAGE_HEIGHT-90, 'DIRECCION GENERAL DE TRANSITO MUNICIPAL')
		canvas.setFont('Times-Bold',9)
		canvas.drawString(485,PAGE_HEIGHT-90, 'DOCUMENTO OFICIAL')
		canvas.setFont('Times-Roman',8)
		canvas.drawString(20,PAGE_HEIGHT-135, 'Por el Concepto de:')
		canvas.line(205, 705,89,705)
		canvas.line(20, 696,590 ,696)
		canvas.line(589, 535,590 ,696)
		canvas.setFont('Times-Bold',8)
		motivo=fields.get('motivo_de_recojimiento',"")
		canvas.drawString(90,PAGE_HEIGHT-135, motivo)
		canvas.setFont('Times-Roman',8)
		#canvas.drawString(210,PAGE_HEIGHT-135, 'N° Infraccion')
		canvas.line(258, 705,309 ,705)
		canvas.setFont('Times-Bold',8)
		activo=fields.get('activo',"")
		canvas.drawString(257,PAGE_HEIGHT-135, activo)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(315,PAGE_HEIGHT-135, 'N° de Parte')
		canvas.line(359, 705,426 ,705)
		canvas.setFont('Times-Bold',8)
		folio_inventario=fields.get('folio_inventario',"")
		canvas.drawString(360,PAGE_HEIGHT-135, folio_inventario)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(430,PAGE_HEIGHT-135, 'Por otro Concepto:')
		canvas.line(359, 705,426 ,705)
		canvas.line(494, 705,590 ,705)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(25,PAGE_HEIGHT-160, 'Lugar del evento:')
		canvas.line(335, 680,85,680)
		canvas.line(20, 535,20 ,696)
		canvas.setFont('Times-Bold',8)
		colonia=fields.get('colonia',"")
		canvas.drawString(85,PAGE_HEIGHT-160, colonia)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(400,PAGE_HEIGHT-160, 'Depositado en: (Pensión)')
		canvas.line(590, 680,489,680)
		canvas.setFont('Times-Bold',8)	
		depositado_en=fields.get('depositado_en',"")
		canvas.drawString(490,PAGE_HEIGHT-160, depositado_en)
		canvas.setFont('Times-Bold',8)
		canvas.drawString(110,PAGE_HEIGHT-185, 'Datos del Vehículo')
		canvas.line(335, 655,175,655)
		canvas.setFont('Times-Bold',8)
		canvas.drawString(420,PAGE_HEIGHT-185, 'Datos de Ingreso a la Pensión')
		canvas.line(590, 655,521,655)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(25,PAGE_HEIGHT-210, 'Marca')
		canvas.line(121, 630,54,630)
		canvas.setFont('Times-Bold',8)	
		marca=fields.get('marca',"")
		canvas.drawString(55,PAGE_HEIGHT-210, marca)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(125,PAGE_HEIGHT-210, 'Tipo')
		canvas.line(201, 630,145,630)
		canvas.setFont('Times-Bold',8)	
		tipo=fields.get('tipo',"")
		canvas.drawString(145,PAGE_HEIGHT-210, tipo)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(205,PAGE_HEIGHT-210, 'Modelo')
		canvas.line(335, 630,235,630)
		canvas.setFont('Times-Bold',8)	
		veh_modelo=fields.get('veh_modelo',"")
		canvas.drawString(235,PAGE_HEIGHT-210, veh_modelo)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(345,PAGE_HEIGHT-210, 'Lugar')
		canvas.line(440, 630,370,630)
		canvas.setFont('Times-Bold',8)
		delegacion=fields.get('delegacion',"")
		canvas.drawString(370,PAGE_HEIGHT-210, delegacion)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(445,PAGE_HEIGHT-210, 'Hora de entrada')
		canvas.line(590, 630,500,630)
		canvas.setFont('Times-Bold',8)
		liberacion_hora=fields.get('liberacion_hora',"")
		canvas.drawString(500,PAGE_HEIGHT-210, liberacion_hora)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(25,PAGE_HEIGHT-235, 'Placas')
		canvas.line(121, 605,49,605)
		canvas.setFont('Times-Bold',8)
		veh_placas=fields.get('veh_placas',"")
		canvas.drawString(50,PAGE_HEIGHT-235, veh_placas)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(125,PAGE_HEIGHT-235, 'Color')
		canvas.line(148, 605,335,605)
		canvas.setFont('Times-Bold',8)
		veh_color=fields.get('veh_color',"")
		canvas.drawString(148,PAGE_HEIGHT-235, veh_color)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(345,PAGE_HEIGHT-235, 'Recibido por:')
		canvas.line(589, 605,392,605)
		canvas.setFont('Times-Bold',8)
		liberacion_recibe=fields.get('liberacion_recibe',"")
		canvas.drawString(393,PAGE_HEIGHT-235, liberacion_recibe)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(25,PAGE_HEIGHT-255, 'Serie de vehículo')
		canvas.line(335, 585,85,585)
		canvas.setFont('Times-Bold',8)
		persona_fisica=fields.get('persona_fisica',"")
		canvas.drawString(85,PAGE_HEIGHT-255, persona_fisica)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(345,PAGE_HEIGHT-255, 'Levantado por la Unidad')
		canvas.line(470, 585,430,585)
		canvas.setFont('Times-Bold',8)
		interior=fields.get('interior',"")
		canvas.drawString(430,PAGE_HEIGHT-255, interior)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(473,PAGE_HEIGHT-255, 'X   Transito')
		canvas.rect(471, 584, 10, 10)
		canvas.setFont('Times-Bold',8)	
		pension_transportado_unidad_transito=fields.get('pension_transportado_unidad_transito',"")
		canvas.drawString(500,PAGE_HEIGHT-255, pension_transportado_unidad_transito)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(25,PAGE_HEIGHT-275, 'Conductor')
		canvas.line(335, 565,65,565)
		canvas.setFont('Times-Bold',8)
		infractor_apepaterno=fields.get('infractor_apepaterno',"")
		canvas.drawString(65,PAGE_HEIGHT-275, infractor_apepaterno)
		#canvas.setStroKeColorRGB(0,0,0)
		canvas.setLineWidth(1)
		canvas.line(20, 535, 590, 535)
		#canvas.setStroKeColorRGB(0,0,0)
		canvas.setLineWidth(1)
		canvas.line(335, 696, 336, 536)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(347,PAGE_HEIGHT-275, 'X   Grua')
		canvas.rect(345, 564, 10, 10)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(390,PAGE_HEIGHT-275, 'X   Particular N°')
		canvas.rect(388, 564, 10, 10)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(347,PAGE_HEIGHT-295, 'X   Por sus medios')
		canvas.rect(345, 544, 10, 10)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(20,PAGE_HEIGHT-320, 'Fecha de Ingreso a pensión')
		canvas.line(228, 520,115,520)
		canvas.setFont('Times-Bold',8)
		pension_fecha=fields.get('pension_fecha',"")
		canvas.drawString(115,PAGE_HEIGHT-320, pension_fecha)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(20,PAGE_HEIGHT-345, 'Fecha de Liberación')
		canvas.line(230, 495,95,495)
		canvas.setFont('Times-Bold',8)	
		fecha_captura=fields.get('fecha_captura',"")
		canvas.drawString(95,PAGE_HEIGHT-345, fecha_captura)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(20,PAGE_HEIGHT-370, 'Hora de Liberación')
		canvas.line(230, 470,95,470)
		canvas.setFont('Times-Bold',8)	
		pension_hora=fields.get('pension_hora',"")
		canvas.drawString(95,PAGE_HEIGHT-370, pension_hora)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(390,PAGE_HEIGHT-370, 'X  Liberado')
		canvas.rect(388, 470, 10, 10)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(230,PAGE_HEIGHT-390, 'Area donde se realiza la Liberación')
		canvas.setFont('Times-Bold',8)	
		calle2=fields.get('calle2',"")
		canvas.drawString(355,PAGE_HEIGHT-390, calle2)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(30,PAGE_HEIGHT-410, 'Nombre de la persona a quien se le entrega:')
		canvas.setFont('Times-Bold',8)	
		liberacion_recibe=fields.get('liberacion_recibe',"")
		canvas.drawString(180,PAGE_HEIGHT-410, liberacion_recibe)
		#canvas.setStroKeColorRGB(0,0,0)
		canvas.setLineWidth(1)
		canvas.line(30, 398, 270, 398)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(80,PAGE_HEIGHT-455, 'Recibí Liberacion de Vehículo')
		canvas.setFont('Times-Bold',8)	
		salida_nombre=fields.get('salida_nombre',"")
		canvas.drawString(100,PAGE_HEIGHT-442, salida_nombre)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(70,PAGE_HEIGHT-465, ' (Para su trámite entre la pensión)')
		#canvas.setStroKeColorRGB(0,0,0)
		canvas.setLineWidth(1)
		canvas.line(585, 400, 345, 400)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(405,PAGE_HEIGHT-455, 'Recibí Vehículo de Conformidad')
		canvas.setFont('Times-Roman',8)
		canvas.drawString(410,PAGE_HEIGHT-465, '(Una vez checado fisicamente)')
		#canvas.setStroKeColorRGB(0,0,0)
		canvas.setLineWidth(1)
		canvas.line(30, 325, 280, 325)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(95,PAGE_HEIGHT-530, 'Firma de quien libera')
		canvas.setFont('Times-Bold',8)	
		liberacion_entrega=fields.get('liberacion_entrega',"")
		canvas.drawString(100,PAGE_HEIGHT-515, liberacion_entrega)
		#canvas.setStroKeColorRGB(0,0,0)
		canvas.setLineWidth(1)
		canvas.line(350, 330, 590, 330)
		canvas.setFont('Times-Roman',8)
		canvas.drawString(445,PAGE_HEIGHT-530, 'Sello')
		canvas.restoreState()
