window.acc_intervino_test=[
        {
                "nombre":"LEON ESPINOZA  JUANO"
                "gafete":"11205"
                "unidad":"T-102"
                "sector":"1ra. Comandancia"
        }
]

window.acc_superviso_test=[
        {"nombre":"MORALES VERA  SERGIO "
        "gafete":"11202"
        "unidad":"T-712"
        "sector":"7ma. Comandancia"}
]

window.acc_test=[
        {
        "id":"abc"
        "folio_accidente":"93"
        "delegacion":"ORIENTE"
        "comandancia":"4TA"
        "turno":"A"
        "fecha":"2013-09-03"
        "hora":"15:09"
        "clasificacion":"Atropello"
        "tipo_choque":"De Frente"
        "latitud":"21.2050057"
        "longitud":"-101.67442169999998"
        "calle1":"AND CECILIO ESTRADA"
        "calle2":"AND EGIPTO"
        "calle3":"AND CULTURA POPULAR"
        "frentea":"123"
        "colonia":"ADQUIRIENTES DE IBARRILLA"
        "estado":"AGUASCALIENTES"
        "municipio":"SAN MIGUEL DE ALLENDE"
        "vehiculos":[]
        "saldoSangres":[
                {
                "disposicion": "CLINICA SAN GABRIEL",
                "domicilio": "Del productor",
                "edad": "12",
                "estado_herido": "Lesionado",
                "levantado_por": "242 CRUZ ROJA",
                "nacionalidad": "Mexicano",
                "nombre": "pedro",
                "se_encontraba": "Pasajero",
                "trasladado_a": "CLINICA SAN GABRIEL"
                }
        ],
        "competenciaJudiciales":[
                {
                "detenido_en": "CLINICA SAN GABRIEL",
                "disposicion": "NO",
                "domicilio": "COMUNIDAD ESTANCIA, CUBO 5",
                "edad": "38",
                "estado_herido": "Detenido",
                "nombre": "JOSE BARAJAS MONJARAZ ARREGLAR COSAS",
                "se_encontraba": "Conductor del Vehiculo 2"
                 }

        ],
        "intervino":acc_intervino_test[0]
        "superviso":acc_superviso_test[0]
        "fotos":["51e2b540331c5d000000000c","51e2b418331c5d000000000b","51e2b307331c5d000000000a"]
        "croquis":"51e2b1a878d80d000000000d"
        "observaciones":"Hola mundo"
        "investigaciones":"Esto es parte de la investigacion"
        "simbologia_croquis":"Esta es la descripcion del croquis"
        "otros":{
            "no_carriles": "2 CARRILES"
            "parte_dia": "Dia"
            "sentido_calle": "UN SENTIDO"
            "tipo_calle": "Calle"
            "visibilidad": "Normal"
        },
        "estado_calles":{
            "alineacion": "Recto Descendente"
            "clima": "Nublado"
            "estado_pavimento": "Empedrado Mojado"
            "regulacion": "Señal de Velocidad"
        },
        "danos":[
            {
            "dueno": "sdasadffadsf"
            "monto": "daasdfasdfads"
            "obj": "Poste Alumbrado"
            "tipo": "123"
            },
            {
            "dueno": "sdafadsf"
            "monto": "dasadfsdasfads"
            "obj": "Poste Alumbrado"
            "tipo": "12dfasdf"
            }
        ]
        "articulos":[
                {
                "id":'23'
                "art":"43"
                "fracc":"C)"
                "descc":"Cuando presente estrelladuras, roturas o esté incompleto y comprenda al 70 % de visibilidad del conductor representando un peligro, será motivo de sanción y cambio obligatorio del mismo."
                },
                {
                "id":'24'
                "art":"122"
                "fracc":"C)"
                "descc":"Los vehículos de propulsión humana o tracción animal provistos de ruedas que no dañen las vías, solo podrán circular en las zonas comerciales que específicamente señale la Dirección de Tránsito, cuyas medidas no deben exceder de 80 cm. de ancho y 2 metros de largo"
                }
        ]

        }
]

window.acc_vehiculos_test = [
        {
        "id": 1
        "intervino_como": "1"
        "clas_vehiculo": "Microbus" 
        "conductor_estado_droga": "EBRIEDAD COMPLETA"   
        "color": "VERDE"    
        "color_detalle": "PALIDO ROJO"  
        "placa": "GC-53207" 
        "modelo": "2013"
        "marca": "NISSAN"
        "submarca": "ALTIMA"
        "capacidad": "750 KGS." 
        "estadov": "GUANAJUATO" 
        "ciudadv": "LEÓN"
        "serie": "NO VISIBLE"
        "tipo": "Chasis y Cabina"
        "datos_adicionales":"DATOS A" 
        "num_economico": "NO"
        "num_grua": "123"
        "pension": "CENTRAL" 
        "vehiculo_servicio":"Servicio Particular"  
        "conductor_nombre": "JOSE BARAJAS MONJARAZ"
        "conductor_apepaterno": "ARREGLAR"
        "conductor_apematerno": "COSAS"
        "conductor_estado":"GUANAJUATO"
        "conductor_municipio":"LEÓN"
        "conductor_calle": "COMUNIDAD ESTANCIA, CUBO 5"
        "conductor_colonia": "SANTA FE" 
        "conductor_edad": "38"
        "conductor_tipo_edad":"AÑOS" 
        "conductor_edo_licencia": "GUANAJUATO" 
        "conductor_num_licencia": "MKL12222545689876341" 
        "conductor_tipo_licencia": "A"
        "conductor_rest_licencia": "Protesis"
        "conductor_fecha_vigencia": "2008-01-01T03:11:45.000Z"
        "conductor_sexo": "HOMBRE"
        "conductor_detenido_en": "CLINICA SAN GABRIEL"
        "conductor_disposicion": "NO"
        "conductor_se_encontraba" :"Conductor del Vehiculo 2" 
        "conductor_levantado_por" :"242 CRUZ ROJA"  
        "conductor_trasladado_a" :"H.G.R."  
        "conductor_custodia":"POLICIA"  
        "dueno_nombre": "MANUEL MEJIA"
        "dueno_calle": "ABASOLO 123"
        "dueno_colonia": "SAN PEDRO DE ABAJO"
        "dueno_tel": "4772567077"
        "dueno_estadop": "GUANAJUATO"
        "dueno_ciudadp": "LEÓN"
        "dueno_cp": "123456"
        "fecha_registro": "2007-03-31T03:11:45.000Z"
        "estado_herido": "Detenido"
        "tipo_dueno":"Nombre"
        "dv_num_inventario": "123"
        "dueno_apepaterno": "SE DESCONOCE"
        "dueno_apematerno": "SE DESCONOCE"
        "folio_infraccion": "123"
        "folio_certificado_medico": "123"
        },
        {
        "id": 1
        "intervino_como": "2"
        "tipo_dueno":"Nombre"
        "conductor_estado_droga": "BAJO INFLUJO DE DROGAS"  
        "clas_vehiculo": "Microbus"    
        "color": "VERDE"    
        "color_detalle": "DESCOLORIDO"  
        "placa": "GC-53207" 
        "modelo": "2003"
        "marca": "NISSAN"
        "submarca": "ALTIMA"
        "capacidad": "750 KGS." 
        "estadov": "GUANAJUATO" 
        "ciudadv": "LEÓN"
        "serie": "NO VISIBLE"
        "tipo": "Chasis y Cabina"
        "datos_adicionales":"DATOS A" 
        "num_economico": "NO"
        "num_grua": "123"
        "pension": "CENTRAL" 
        "vehiculo_servicio":"Servicio Publico"  
        "conductor_nombre": "JOSE BARAJAS MONJARAZ"
        "conductor_apepaterno": "ARREGLAR"
        "conductor_apematerno": "COSAS"
        "conductor_estado":"GUANAJUATO"
        "conductor_municipio":"LEÓN"
        "conductor_calle": "COMUNIDAD ESTANCIA, CUBO 5"
        "conductor_colonia": "SANTA FE" 
        "conductor_edad": "38"
        "conductor_tipo_edad":"AÑOS" 
        "conductor_edo_licencia": "GUANAJUATO" 
        "conductor_num_licencia": "MKL12222545689876341" 
        "conductor_tipo_licencia": "A"
        "conductor_rest_licencia": "Protesis"
        "conductor_fecha_vigencia": "2008-01-01T03:11:45.000Z"
        "conductor_sexo": "HOMBRE"
        "conductor_detenido_en": "CLINICA SAN GABRIEL"
        "conductor_disposicion": "NO"
        "conductor_se_encontraba" :"Conductor del Vehiculo 2" 
        "conductor_levantado_por" :"242 CRUZ ROJA"  
        "conductor_trasladado_a" :"H.G.R."  
        "conductor_custodia":"NO"  
        "dueno_nombre": "SE DESCONOCE"
        "dueno_calle": "SE DESCONOCE"
        "dueno_colonia": "SANTA FE"
        "dueno_tel": "--"
        "dueno_estadop": "GUANAJUATO"
        "dueno_ciudadp": "LEÓN"
        "dueno_cp": "--"
        "fecha_registro": "2007-03-31T03:11:45.000Z"
        "estado_herido": "Lesionado"
        "dv_num_inventario": "123"
        "dueno_apepaterno": "SE DESCONOCE"
        "dueno_apematerno": "SE DESCONOCE"
        "folio_infraccion": "123"
        "folio_certificado_medico": "123"
        "vehiculo_servicio": "Servicio"
        }
        ,{
        "id": 2
        "intervino_como": "2"
        "tipo_dueno":"Nombre"
        "conductor_estado_droga": "ALIENTO ALCOHOLICO"  
        "clas_vehiculo": "Motocicleta"    
        "color": "VERDE"    
        "color_detalle": "DESCOLORIDO"  
        "placa": "GC-53207" 
        "modelo": "2003"
        "marca": "NISSAN"
        "submarca": "ALTIMA"
        "capacidad": "750 KGS." 
        "estadov": "GUANAJUATO" 
        "ciudadv": "LEÓN"
        "serie": "NO VISIBLE"
        "tipo": "Chasis y Cabina"
        "datos_adicionales":"DATOS A" 
        "num_economico": "NO"
        "num_grua": "123"
        "pension": "CENTRAL" 
        "vehiculo_servicio":"Servicio Publico"  
        "conductor_nombre": "JOSE BARAJAS MONJARAZ"
        "conductor_apepaterno": "ARREGLAR"
        "conductor_apematerno": "COSAS"
        "conductor_estado":"GUANAJUATO"
        "conductor_municipio":"LEÓN"
        "conductor_calle": "COMUNIDAD ESTANCIA, CUBO 5"
        "conductor_colonia": "SANTA FE" 
        "conductor_edad": "38"
        "conductor_tipo_edad":"AÑOS" 
        "conductor_edo_licencia": "GUANAJUATO" 
        "conductor_num_licencia": "MKL12222545689876341" 
        "conductor_tipo_licencia": "A"
        "conductor_rest_licencia": "Protesis"
        "conductor_fecha_vigencia": "2008-01-01T03:11:45.000Z"
        "conductor_sexo": "HOMBRE"
        "conductor_detenido_en": "CLINICA SAN GABRIEL"
        "conductor_disposicion": "NO"
        "conductor_se_encontraba" :"Conductor del Vehiculo 2" 
        "conductor_levantado_por" :"242 CRUZ ROJA"  
        "conductor_trasladado_a" :"H.G.R."  
        "conductor_custodia":"NO"  
        "dueno_nombre": "SE DESCONOCE"
        "dueno_calle": "SE DESCONOCE"
        "dueno_colonia": "SANTA FE"
        "dueno_tel": "--"
        "dueno_estadop": "GUANAJUATO"
        "dueno_ciudadp": "LEÓN"
        "dueno_cp": "--"
        "fecha_registro": "2007-03-31T03:11:45.000Z"
        "estado_herido": "Lesionado y Detenido"
        "dv_num_inventario": "123"
        "dueno_apepaterno": "SE DESCONOCE"
        "dueno_apematerno": "SE DESCONOCE"
        "folio_infraccion": "123"
        "folio_certificado_medico": "123"
        "vehiculo_servicio": "Servicio"
        }
        ,{
        "id": 1
        "intervino_como": "3"
        "tipo_dueno":"Razon Social"
        "clas_vehiculo": "Bicicleta"  
        "conductor_estado_droga": "ESTADO NORMAL"    
        "color": "VERDE"    
        "color_detalle": "DESCOLORIDO"  
        "placa": "GC-53207" 
        "modelo": "2003"
        "marca": "NISSAN"
        "submarca": "ALTIMA"
        "capacidad": "750 KGS." 
        "estadov": "GUANAJUATO" 
        "ciudadv": "LEÓN"
        "serie": "NO VISIBLE"
        "tipo": "Chasis y Cabina"
        "datos_adicionales":"DATOS A" 
        "num_economico": "NO"
        "num_grua": "123"
        "pension": "CENTRAL" 
        "vehiculo_servicio":"Servicio Publico"  
        "conductor_nombre": "JOSE BARAJAS MONJARAZ"
        "conductor_apepaterno": "ARREGLAR"
        "conductor_apematerno": "COSAS"
        "conductor_estado":"GUANAJUATO"
        "conductor_municipio":"LEÓN"
        "conductor_calle": "COMUNIDAD ESTANCIA, CUBO 5"
        "conductor_colonia": "SANTA FE" 
        "conductor_edad": "38"
        "conductor_tipo_edad":"AÑOS" 
        "conductor_edo_licencia": "GUANAJUATO" 
        "conductor_num_licencia": "MKL12222545689876341" 
        "conductor_tipo_licencia": "A"
        "conductor_rest_licencia": "Protesis"
        "conductor_fecha_vigencia": "2008-01-01T03:11:45.000Z"
        "conductor_sexo": "HOMBRE"
        "conductor_detenido_en": "CLINICA SAN GABRIEL"
        "conductor_disposicion": "NO"
        "conductor_se_encontraba" :"Conductor del Vehiculo 2" 
        "conductor_levantado_por" :"242 CRUZ ROJA"  
        "conductor_trasladado_a" :"NINGUNO"  
        "conductor_custodia":"NO"  
        "dueno_nombre": "SE DESCONOCE"
        "dueno_calle": "SE DESCONOCE"
        "dueno_colonia": "SANTA FE"
        "dueno_tel": "--"
        "dueno_estadop": "GUANAJUATO"
        "dueno_ciudadp": "LEÓN"
        "dueno_cp": "--"
        "fecha_registro": "2007-03-31T03:11:45.000Z"
        "estado_herido": "Finado"
        "dv_num_inventario": "123"
        "dueno_apepaterno": "SE DESCONOCE"
        "dueno_apematerno": "SE DESCONOCE"
        "folio_infraccion": "123"
        "folio_certificado_medico": "123"
        "vehiculo_servicio": "Servicio"
        },
        {
        "id": 1
        "intervino_como": "4"
        "tipo_dueno":"Razon Social"
        "clas_vehiculo": "Otros"    
        "color": "VERDE"    
        "conductor_estado_droga": "INCONSCIENTE"  
        "color_detalle": "DESCOLORIDO"  
        "placa": "GC-53207" 
        "modelo": "2013"
        "marca": "CHEVROLET"
        "submarca": "ALTIMA"
        "capacidad": "750 KGS." 
        "estadov": "GUANAJUATO" 
        "ciudadv": "LEÓN"
        "serie": "NO VISIBLE"
        "tipo": "Chasis y Cabina"
        "datos_adicionales":"DATOS A" 
        "num_economico": "NO"
        "num_grua": "123"
        "pension": "CENTRAL" 
        "vehiculo_servicio":"Servicio Publico Federal"  
        "conductor_nombre": "JOSE BARAJAS MONJARAZ"
        "conductor_apepaterno": "ARREGLAR"
        "conductor_apematerno": "COSAS"
        "conductor_estado":"GUANAJUATO"
        "conductor_municipio":"LEÓN"
        "conductor_calle": "COMUNIDAD ESTANCIA, CUBO 5"
        "conductor_colonia": "SANTA FE" 
        "conductor_edad": "38"
        "conductor_tipo_edad":"AÑOS" 
        "conductor_edo_licencia": "GUANAJUATO" 
        "conductor_num_licencia": "MKL12222545689876341" 
        "conductor_tipo_licencia": "A"
        "conductor_rest_licencia": "Protesis"
        "conductor_fecha_vigencia": "2008-01-01T03:11:45.000Z"
        "conductor_sexo": "HOMBRE"
        "conductor_detenido_en": "CLINICA SAN GABRIEL"
        "conductor_disposicion": "NO"
        "conductor_se_encontraba" :"Conductor del Vehiculo 2" 
        "conductor_levantado_por" :"242 CRUZ ROJA"  
        "conductor_trasladado_a" :"NINGUNO"  
        "conductor_custodia":"NO"  
        "dueno_nombre": "SE DESCONOCE"
        "dueno_calle": "SE DESCONOCE"
        "dueno_colonia": "SANTA FE"
        "dueno_tel": "--"
        "dueno_estadop": "GUANAJUATO"
        "dueno_ciudadp": "LEÓN"
        "dueno_cp": "--"
        "fecha_registro": "2007-03-31T03:11:45.000Z"
        "estado_herido": "Lesionado"
        "dv_num_inventario": "123"
        "dueno_apepaterno": "SE DESCONOCE"
        "dueno_apematerno": "SE DESCONOCE"
        "folio_infraccion": "123"
        "folio_certificado_medico": "123"
        "vehiculo_servicio": "Servicio Public"
        }

]