window.pre_test=[
	{
	"id":"10"
	"fecha_hora":"5:45"
	"numero_de_folio":"45436"
	"delegacion":"Delegacion Hermanos Aldama"
	"comandancia":"Primera Comandancia"
	"turno":"Turno B"
	"tipo_de_evento":"Rana"
	"clasificacion_de_accidente":"Atropello"
	"calle_1":"BLVD SAN PEDRO"
	"calle_2":"BLVD AEROPUERTO"
	"colonia":"10 de mayo"
	"operativo":"Temporada de feria"
	"no_vehiculos_participantes":"12"
	"no_de_detenidos":"34"
	"no_de_heridos":"5"
	"no_de_muertos":"0"
	"pension":"Central"
	"no_de_inventario":"2335"
	"agente":"111--MEJIA JUAN"
	"unidad":"54"
	"observaciones":"Bien malo" 
    },
	{
	"id":"11"
	"fecha-hora":"5:45"
	"numero_de_folio":"45436"
	"delegacion":"Delegacion Hermanos Aldama"
	"comandancia":"Primera Comandancia"
	"turno":"Turno B"
	"tipo_de_evento":"Rana"
	"clasificacion_de_accidente":"Atropello"
	"calle_1":"BLVD SAN PEDRO"
	"calle_2":"BLVD AEROPUERTO"
	"colonia":"10 de mayo"
	"operativo":"Temporada de feria"
	"no_vehiculos_participantes":"12"
	"no_de_detenidos":"34"
	"no_de_heridos":"5"
	"no_de_muertos":"0"
	"pension":"Central"
	"no_de_inventario":"2335"
	"agente":"111--MEJIA JUAN"
	"unidad":"54"
	"observaciones":"bien mal"
	}
]
